//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITApexWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbITApexEntities : DbContext
    {
        public DbITApexEntities()
            : base("name=DbITApexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tbl_SlideImage> tbl_SlideImage { get; set; }
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<tblCartStatu> tblCartStatus { get; set; }
        public virtual DbSet<tblMemberRole> tblMemberRoles { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblShippingDetail> tblShippingDetails { get; set; }
        public virtual DbSet<tblCategory_u> tblCategory_u { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblProduct_u> tblProduct_u { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }

        public System.Data.Entity.DbSet<ITApexWebsite.Models.UserProductDisplay> UserProductDisplays { get; set; }
    }
}
