//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITApexWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class secOrderDetail
    {
        public int Id { get; set; }
        public int product_id { get; set; }
        public string price { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual secShippingDetail secShippingDetail { get; set; }
        public virtual securityProduct securityProduct { get; set; }
    }
}
