//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITApexWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class securityProduct
    {
        public int s_Id { get; set; }
        public string s_name { get; set; }
        public string s_img { get; set; }
        public string s_desc { get; set; }
        public Nullable<int> s_quan { get; set; }
        public Nullable<System.DateTime> s_createdDate { get; set; }
        public Nullable<System.DateTime> s_modifiedDate { get; set; }
        public Nullable<bool> isFeatured { get; set; }
        public Nullable<bool> isActice { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> s_price { get; set; }
    }
}
