//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITApexWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public int cart_Id { get; set; }
        public Nullable<int> cart_fk_pro { get; set; }
        public Nullable<int> u_Id { get; set; }
        public Nullable<int> cartStatus_Id { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
