//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITApexWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct_u
    {
        public int p_Id { get; set; }
        public string p_name { get; set; }
        public string p_img { get; set; }
        public Nullable<int> p_price { get; set; }
        public string p_desc { get; set; }
        public Nullable<int> p_quantity { get; set; }
        public Nullable<int> p_fk_user { get; set; }
        public Nullable<int> p_fk_Category { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblCategory tblCategory { get; set; }
    }
}
