//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITApexWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShippingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblShippingDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int shipping_Id { get; set; }
        public string pincode { get; set; }
        public Nullable<int> order_Id { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
        public string payment_type { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddress { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
